### ISSUE TITLE
Error resolving expo-asset-utils

### ISSUE THREAD

**Issue by mattdufeu** [expo/expo-asset-utils#14]
I'm trying to follow the "Creating a 2D game" tutorial and started off running https://snack.expo.io/@community/flappy-bird.

Unfortunately I'm getting the above error.

**Comment by sjchmiela** [comment]
Are you sure you have added `expo-asset-utils` to `package.json` either by the following button or by adding an entry in `package.json`? I hope you've found a way to fix your issue!

![Zrzut ekranu 2019-03-22 o 16 37 31](https://user-images.githubusercontent.com/1151041/54834618-cbe93180-4cc0-11e9-8a4e-eccdc5b7d258.png)
