### ISSUE TITLE
Could not find image file ...

### ISSUE THREAD

**Issue by i8ramin** [expo/expo-asset-utils#4]
`AssetUtils.resolveAsync` will fail with certain URL paths. It seems to be related to some encoded characters in the path (FYI, these are assets uploaded to Firebase cloud storage, nested under a bucket folder structure). For example the following URL path fails with the error message below.

https://firebasestorage.googleapis.com/v0/b/slpbookcompanion.appspot.com/o/flamelink%2Fmedia%2F1521796272423_brown-bear.jpg?alt=media&token=9ee34412-a306-420d-ab1c-1ab962ccfcfe

```
Could not find image file:///Users/local/Library/Developer/CoreSimulator/Devices/EC81755E-8C3F-4B28-95B7-B1687DF803F8/data/Containers/Data/Application/6E8622EF-7D73-4503-9005-06E55B496B6B/Library/Caches/ExponentExperienceData/%2540local%252Fslpbookcompanion-expo/flamelink/media/1521796272423_brown-bear.jpg 
```

When I navigate to that folder path locally on my machine, the file is indeed missing. If i use a simpler URL of an image, like the one provided in the sample code, it works just fine. My hunch is that it is related to the `%2F` in the url that is throwing it off. Comparing the actual image URL to the local filepath it is trying to look for it I see:

**/flamelink%2Fmedia%2F1521796272423_brown-bear.jpg** (the URL)
**/flamelink/media/1521796272423_brown-bear.jpg** (local file path)

It looks like it is decoding the *%2F* to */* and that is why it fails

**Comment by i8ramin** [comment]
**Update:** I ended up "fixing" the issue by manually defining a **filename** based on my record's ID and then passing the resulting `Asset` (derived from `fromUriAsync`) to `resolveAsync`.

```
const filename = `book-${book.id}.jpg`
const asset = await AssetUtils.fromUriAsync(image.uri, filename)

const imageSource = await AssetUtils.resolveAsync(asset)
```

If `resolveAsync` would also accept a "filename" as a 2nd parameter, this could be simplified.

**Comment by EvanBacon** [comment]
Duplicate: #2
