### ISSUE TITLE
Strage Error on Android

### ISSUE THREAD

**Issue by pivanov** [expo/expo-asset-utils#5]
Hey guys I had the following:

import AssetUtils from 'expo-asset-utils'
...
const filename = `screenshot-${i}.png`
const asset = await AssetUtils.fromUriAsync(uri, filename)
...
the `uri` is content://media/external/images/media/27

the error I receive is:
[Error: unexpected url: content://media/external/images/media/27]

Any ideas? It works fine on iOS

**Comment by gogogous88** [comment]
very the same issue, work on iOS but not work on android

**Comment by EvanBacon** [comment]
Noticed lot's of weirdness with file loading on android in React Native. I'm investigating now

**Comment by Lidanha** [comment]
Hey is there a workaround for this?

**Comment by EvanBacon** [comment]
I can look at it this week. In RN we use the fetch API to load files. For whatever reason loading binary files in Android doesn't work, I don't think it's related to this issue. You also cannot save a b64 and get a localURI cuz RN.ImageStore isn't supported on Android 😱 point being that android has a bunch of file system features missing 😩 Expo.FileSystem could potentially solve these issues, I would just have to add some native code. Tried last week but we were doing a bunch of refactoring. But always on my mind 😁

**Comment by Lidanha** [comment]
Thanks, I appreciate your support. My team is really stuck.. 😢 We can't use expo-pixi because it uses expo-asset-utils that has this issue.

**Comment by Lidanha** [comment]
Hey @EvanBacon,

Any news about this issue?

Thanks :-)

**Comment by jlongshore** [comment]
Same issue with Android - needing to use expo-pixi in the same manner as @Lidanha

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/pull/2328 able to be fixed in SDK31
